import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "bitzoom/open-api",
    },
    {
      type: "category",
      label: "quotations",
      link: {
        type: "doc",
        id: "bitzoom/quotations",
      },
      items: [
        {
          type: "doc",
          id: "bitzoom/api-quotations-getdepth",
          label: "/api/quotations/getdepth",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-quotations-getfundingrate",
          label: "/api/quotations/getfundingrate",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-quotations-getkline",
          label: "/api/quotations/getkline",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-quotations-getmarkets",
          label: "/api/quotations/getmarkets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-quotations-getorders",
          label: "/api/quotations/getorders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-quotations-getpositions",
          label: "/api/quotations/getpositions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-quotations-getprice",
          label: "/api/quotations/getprice",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-quotations-getticker",
          label: "/api/quotations/getticker",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-quotations-gettrades",
          label: "/api/quotations/gettrades",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-quotations-newfund",
          label: "/api/quotations/newfund",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-quotations-newfundingrate",
          label: "/api/quotations/newfundingrate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-quotations-newmarket",
          label: "/api/quotations/newmarket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-quotations-neworder",
          label: "/api/quotations/neworder",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-quotations-newtrade",
          label: "/api/quotations/newtrade",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "cobo",
      link: {
        type: "doc",
        id: "bitzoom/cobo",
      },
      items: [
        {
          type: "doc",
          id: "bitzoom/api-cobo-callback",
          label: "/api/cobo/callback",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-cobo-depositrecord",
          label: "/api/cobo/depositrecord",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-cobo-getaddress",
          label: "/api/cobo/getaddress",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-cobo-getchain",
          label: "/api/cobo/getchain",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-cobo-gettoken",
          label: "/api/cobo/gettoken",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-cobo-webhook",
          label: "/api/cobo/webhook",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-cobo-withdraw",
          label: "/api/cobo/withdraw",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-cobo-withdrawrecord",
          label: "/api/cobo/withdrawrecord",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "users",
      link: {
        type: "doc",
        id: "bitzoom/users",
      },
      items: [
        {
          type: "doc",
          id: "bitzoom/api-users-depositrecord",
          label: "/api/users/depositrecord",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-users-getaddress",
          label: "/api/users/getaddress",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-users-getaddresswhite",
          label: "/api/users/getaddresswhite",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-users-getchain",
          label: "/api/users/getchain",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-users-setaddresswhite",
          label: "/api/users/setaddresswhite",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-users-updatedeposit",
          label: "/api/users/updatedeposit",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-users-updatewithdraw",
          label: "/api/users/updatewithdraw",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-users-withdraw",
          label: "/api/users/withdraw",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-users-withdrawrecord",
          label: "/api/users/withdrawrecord",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "gateway",
      link: {
        type: "doc",
        id: "bitzoom/gateway",
      },
      items: [
        {
          type: "doc",
          id: "bitzoom/api-gateway-ping",
          label: "/api/gateway/ping",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-gateway-time",
          label: "/api/gateway/time",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-adlquantile",
          label: "/api/v1/adlquantile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-balance",
          label: "/api/v1/balance",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-commissionrate",
          label: "/api/v1/commissionrate",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-deleteorder",
          label: "/api/v1/deleteorder",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-depth",
          label: "/api/v1/depth",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-exchangeinfo",
          label: "/api/v1/exchangeinfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-historyorder",
          label: "/api/v1/historyorder",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-historyposition",
          label: "/api/v1/historyposition",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-historypositionmargin",
          label: "/api/v1/historypositionmargin",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-historytrade",
          label: "/api/v1/historytrade",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-klines",
          label: "/api/v1/klines",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-leverage",
          label: "/api/v1/leverage",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-margintype",
          label: "/api/v1/margintype",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-myfavorite",
          label: "/api/v1/myfavorite",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-openinterest",
          label: "/api/v1/openinterest",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-openorders",
          label: "/api/v1/openorders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-order",
          label: "/api/v1/order",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-positionmargin",
          label: "/api/v1/positionmargin",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-positionrisk",
          label: "/api/v1/positionrisk",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-premiumindex",
          label: "/api/v1/premiumindex",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-symbolcategories",
          label: "/api/v1/symbolcategories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-ticker",
          label: "/api/v1/ticker",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-ticker-bookticker",
          label: "/api/v1/ticker/bookticker",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-ticker-hr-24",
          label: "/api/v1/ticker/hr24",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-ticker-price",
          label: "/api/v1/ticker/price",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-trades",
          label: "/api/v1/trades",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-userinfohook",
          label: "/api/v1/userinfohook",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-wallet-depositrecord",
          label: "/api/v1/wallet/depositrecord",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-wallet-getaddresswhite",
          label: "/api/v1/wallet/getaddresswhite",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-wallet-getchain",
          label: "/api/v1/wallet/getchain",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-wallet-gettoken",
          label: "/api/v1/wallet/gettoken",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-wallet-setaddresswhite",
          label: "/api/v1/wallet/setaddresswhite",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-wallet-withdraw",
          label: "/api/v1/wallet/withdraw",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-wallet-withdrawrecord",
          label: "/api/v1/wallet/withdrawrecord",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "exchange",
      link: {
        type: "doc",
        id: "bitzoom/exchange",
      },
      items: [
        {
          type: "doc",
          id: "bitzoom/api-exchange-getassets",
          label: "/api/exchange/getassets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-exchange-getmarkets",
          label: "/api/exchange/getmarkets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-exchange-setasset",
          label: "/api/exchange/setasset",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-exchange-verificationuser",
          label: "/api/exchange/verificationuser",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "funds",
      link: {
        type: "doc",
        id: "bitzoom/funds",
      },
      items: [
        {
          type: "doc",
          id: "bitzoom/api-funds-bill",
          label: "/api/funds/bill",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-funds-deposit",
          label: "/api/funds/deposit",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-funds-freezefund",
          label: "/api/funds/freezefund",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-funds-getaccount",
          label: "/api/funds/getaccount",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-funds-getaccounttype",
          label: "/api/funds/getaccounttype",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-funds-getbill",
          label: "/api/funds/getbill",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-funds-getfunds",
          label: "/api/funds/getfunds",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-funds-getmarketaccount",
          label: "/api/funds/getmarketaccount",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-funds-unfreezefund",
          label: "/api/funds/unfreezefund",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-funds-withdraw",
          label: "/api/funds/withdraw",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "positions",
      link: {
        type: "doc",
        id: "bitzoom/positions",
      },
      items: [
        {
          type: "doc",
          id: "bitzoom/api-positions-cancelorder",
          label: "/api/positions/cancelorder",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-positions-cleardata",
          label: "/api/positions/cleardata",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-positions-getfundingrate",
          label: "/api/positions/getfundingrate",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-positions-getopenmargin",
          label: "/api/positions/getopenmargin",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-positions-getorders",
          label: "/api/positions/getorders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-positions-getpositions",
          label: "/api/positions/getpositions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-positions-getprice",
          label: "/api/positions/getprice",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-positions-newmarket",
          label: "/api/positions/newmarket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-positions-placeorder",
          label: "/api/positions/placeorder",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-positions-testprice",
          label: "/api/positions/testprice",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-positions-tradenotice",
          label: "/api/positions/tradenotice",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "trades",
      link: {
        type: "doc",
        id: "bitzoom/trades",
      },
      items: [
        {
          type: "doc",
          id: "bitzoom/api-trades-cancelorders",
          label: "/api/trades/cancelorders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-trades-cleardata",
          label: "/api/trades/cleardata",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-trades-getmarketprice",
          label: "/api/trades/getmarketprice",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-trades-getmarkets",
          label: "/api/trades/getmarkets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-trades-getorderbooks",
          label: "/api/trades/getorderbooks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-trades-getorders",
          label: "/api/trades/getorders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-trades-gettrades",
          label: "/api/trades/gettrades",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-trades-newmarket",
          label: "/api/trades/newmarket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-trades-placeorder",
          label: "/api/trades/placeorder",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
