import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "bitzoom/open-api",
    },
    {
      type: "category",
      label: "gateway",
      link: {
        type: "doc",
        id: "bitzoom/gateway",
      },
      items: [
        {
          type: "doc",
          id: "bitzoom/api-gateway-ping",
          label: "Ping",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-gateway-time",
          label: "Time",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-adlquantile",
          label: "AdlQuantile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-balance",
          label: "Balance",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-commissionrate",
          label: "CommissionRate",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-deleteorder",
          label: "DeleteOrder",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-depth",
          label: "Depth",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-exchangeinfo",
          label: "ExchangeInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-fundingfeehistory",
          label: "FundingFeeHistory",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-historyorder",
          label: "HistoryOrder",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-historyposition",
          label: "HistoryPosition",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-historypositionmargin",
          label: "HistoryPositionMargin",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-historytrade",
          label: "HistoryTrade",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-klines",
          label: "Klines",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-leverage",
          label: "Leverage",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-margintype",
          label: "MarginType",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-myfavorite",
          label: "MyFavorite",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-openinterest",
          label: "OpenInterest",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-openorders",
          label: "OpenOrders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-order",
          label: "Order",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-overview",
          label: "Overview",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-positionmargin",
          label: "PositionMargin",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-positionrisk",
          label: "PositionRisk",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-premiumindex",
          label: "PremiumIndex",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-symbolcategories",
          label: "SymbolCategories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-symbolinfo",
          label: "SymbolInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-ticker",
          label: "Ticker",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-ticker-bookticker",
          label: "BookTicker",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-ticker-hr-24",
          label: "Hr24",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-ticker-price",
          label: "Price",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-tradeinfo",
          label: "TradeInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-trades",
          label: "Trades",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-userinfohook",
          label: "UserInfoHook",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-volumeintervaltype",
          label: "VolumeIntervalType",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-wallet-depositrecord",
          label: "DepositRecord",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-wallet-getaddresswhite",
          label: "GetAddressWhite",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-wallet-getchain",
          label: "GetChain",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-wallet-gettoken",
          label: "GetToken",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-wallet-setaddresswhite",
          label: "SetAddressWhite",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-wallet-withdraw",
          label: "Withdraw",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "bitzoom/api-v-1-wallet-withdrawrecord",
          label: "WithdrawRecord",
          className: "api-method get",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
